Madb.Site/Models/Documentation/ClassModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Camalot.Common.Extensions;

namespace Madb.Site.Models.Documentation {
	public class ClassModel {
		public ClassModel() {
			Methods = new List<MethodModel>();
			Properties = new List<PropertyModel>();
		}
		public string Name { get; set; }
		public string Description { get; set; }
		public string Namespace { get; set; }
		public string Assembly { get; set; }
		public Xml.Member Documentation { get; set; }
		public string XmlName { get; set; }
		public bool Ignore { get { return Documentation != null && Documentation.Ignore; } }
		public bool IsStatic { get; set; }

		public IList<MethodModel> Methods {get;set;}

		public IList<PropertyModel> Properties { get; set; }

		public string Id {
			get {
				return "{0}.{1}".With(Namespace, Name).Slug();
			}
		}

		public override string ToString() {
			return "{0}.{1}".With(Namespace, Name);
		}
	}
}

Madb.Site/Models/Documentation/MethodModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Camalot.Common.Extensions;
using Madb.Site.Extensions;
namespace Madb.Site.Models.Documentation {
	public class MethodModel {
		public MethodModel() {
			Parameters = new List<ParameterModel>();
			GenericParameters = new List<TypeModel>();
		}
		public string Name { get; set; }
		public Xml.Member Documentation { get; set; }
		public string XmlName { get; set; }
		public bool Ignore { get { return Documentation != null && Documentation.Ignore; } }
		public Type ReturnType { get; set; }
		public Type Parent { get; set; }
		public IList<ParameterModel> Parameters { get; set; }
		public IList<TypeModel> GenericParameters { get; set; }
		public bool IsStatic { get; set; }
		public bool IsExtension {
			get {
				return ExtensionOf != null;
			}
		}
		public Type ExtensionOf { get; set; }

		public string Id {
			get {
				return "{0}.{1}".With(Parent.ToSafeFullName(), Name).Slug();
			}
		}

		public override string ToString() {
			if(ExtensionOf == null) {
				return "{0}{2} ( {1} )".With(Name, String.Join(", ", Parameters.Select(p => p.ToString())), GenericParameters != null && GenericParameters.Count > 0 ? "<{0}>".With(String.Join(", ", GenericParameters.Select(g => g.ToString()))) : "");
			} else {
				return "{0}{2} ( {1} )".With(
					Name,
					String.Join(", ", Parameters.Skip(1).Select(p => p.ToString())),
					GenericParameters != null && GenericParameters.Count > 0 ? "<{0}>".With(String.Join(", ", GenericParameters.Select(g => g.ToString()))) : ""
				);
			}
		}
	}
}

Madb.Site/Models/Documentation/NamespaceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Camalot.Common.Extensions;

namespace Madb.Site.Models.Documentation {
	public class NamespaceModel {
		public NamespaceModel() {
			Classes = new List<ClassModel>();
			Namespaces = new List<NamespaceModel>();
		}
		public string Name { get; set; }
		public IList<NamespaceModel> Namespaces { get; set; }
		public IList<ClassModel> Classes { get; set; }
		public bool Ignore { get { return Classes.Where(c => !c.Ignore).Count() == 0 && Namespaces.Where(c => !c.Ignore).Count() == 0; } }
		public String AssemblyVersion { get; set; }

		public string Id {
			get {
				return Name.Slug();
			}
		}

		public override string ToString() {
			return this.Name;
		}
	}
}

Madb.Site/Models/Documentation/ParameterModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Camalot.Common.Extensions;

namespace Madb.Site.Models.Documentation {
	public class ParameterModel {
		public string Name { get; set; }
		public TypeModel Type { get; set; }
		public bool IsOut { get; set; }
		public bool IsIn { get; set; }
		public bool IsOptional { get; set; }

		public override string ToString() {
			return "{4}{2}{3}{0} {1}{5}".With(Type.ToString(), Name, IsOut ? "{out}" : "", IsIn ? "{in}" : "", IsOptional ? "[" : "", IsOptional ? "]" : "");
		}
	}
}

Madb.Site/Models/Documentation/PropertyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Camalot.Common.Extensions;
using Madb.Site.Extensions;

namespace Madb.Site.Models.Documentation {
	public class PropertyModel {
		public string Name { get; set; }
		public Xml.Member Documentation { get; set; }
		public string XmlName { get; set; }
		public bool Ignore { get { return Documentation != null && Documentation.Ignore; } }
		public Type ReturnType { get; set; }
		public Type Parent { get; set; }
		public bool IsStatic { get; set; }
		public bool IsReadOnly { get; set; }
		public string Id {
			get {
				return "{0}.{1}".With(Parent.ToSafeFullName(), Name).Slug();
			}
		}

		public override string ToString() {
			return Name;
		}
	}
}

Madb.Site/Models/Documentation/TypeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Camalot.Common.Extensions;
using Madb.Site.Extensions;

namespace Madb.Site.Models.Documentation {
	public class TypeModel {
		public Type BaseType { get; set; }
		public string Name { get; set; }
		public override string ToString() {
			return BaseType.ToSafeName();
		}
	}
}

Madb.Site/Models/Documentation/Xml/Assembly.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace Madb.Site.Models.Documentation.Xml {
	public class Assembly {
		[XmlElement("name")]
		public string Name { get; set; }
	}
}

Madb.Site/Models/Documentation/Xml/Document.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace Madb.Site.Models.Documentation.Xml {
	[XmlRoot("doc")]
	public class Document {
		[XmlArrayItem("member")]
		[XmlArray("members")]
		public IList<Member> Members { get; set; }
	}
}

Madb.Site/Models/Documentation/Xml/Gist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

namespace Madb.Site.Models.Documentation.Xml {
	public class Gist {
		[XmlAttribute("id")]
		public string Id { get; set; }
		[XmlText]
		public string Description { get; set; }
	}
}

Madb.Site/Models/Documentation/Xml/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Xml;
using System.Xml.Serialization;

namespace Madb.Site.Models.Documentation.Xml {
	[XmlRoot("member")]
	public class Member {
		[XmlAttribute("name")]
		public string Name { get; set; }
		[XmlElement("summary")]
		public List<Simple> Summary { get; set; }
		[XmlElement("typeparam")]
		public List<Param> TypeParams { get; set; }
		[XmlElement("param")]
		public List<Param> Params { get; set; }
		[XmlElement("returns")]
		public List<Simple> Returns { get; set; }
		[XmlElement("gist")]
		public List<Gist> Gists { get; set; }
		[XmlElement("remarks")]
		public List<Simple> Remarks { get; set; }
		[XmlElement("example")]
		public List<Simple> Examples { get; set; }
		[XmlElement("exception")]
		public List<Reference> Exceptions { get; set; }
		[XmlElement("permission")]
		public List<Reference> Permissions { get; set; }
		[XmlElement("see")]
		public List<Reference> Sees { get; set; }
		[XmlElement("seealso")]
		public List<Reference> SeeAlsos { get; set; }
		[XmlElement("value")]
		public List<Simple> Values { get; set; }
		[XmlElement("ignore")]
		[DefaultValue(false)]
		public bool Ignore { get; set; }
	}
}

Madb.Site/Models/Documentation/Xml/Param.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

namespace Madb.Site.Models.Documentation.Xml {
	public class Param {
		[XmlAttribute("name")]
		public string Name { get; set; }
		[XmlText]
		public string Value { get; set; }
	}
}

Madb.Site/Models/Documentation/Xml/Reference.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace Madb.Site.Models.Documentation.Xml {
	public class Reference {
		[XmlAttribute("cref")]
		public string Link { get; set; }
		[XmlText]
		public string Description { get; set; }
	}
}

Madb.Site/Models/Documentation/Xml/Simple.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml;
using System.Xml.Serialization;

namespace Madb.Site.Models.Documentation.Xml {
	public class Simple {
		[XmlIgnore]
		public string Value { get; set; }

		[XmlText]
		public XmlNode[] CDataContent {
			get {
				var dummy = new XmlDocument();
				return new XmlNode[] { dummy.CreateCDataSection(Value) };
			}
			set {
				if(value == null) {
					Value = null;
					return;
				}
				Value = string.Join(" ", value.Select(a => a.OuterXml)).Trim();
			}
		}

		public override string ToString() {
			return Value;
		}
	}
}

Madb.Site/Controllers/DocumentationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Madb.Site.Services;

namespace Madb.Site.Controllers {
	public class DocumentationController : Controller {
		// GET: Documentation
		public ActionResult Index(String id) {
			var builder = new DocumentationService();
			var model = builder.Build(id);
			return View(model);
		}

		public PartialViewResult Navigation(string id) {
			var builder = new DocumentationService();
			var model = builder.Build(id);
			return this.PartialView(model);
		}
	}
}

Madb.Site/Views/Documentation/Index.cshtml
@model Madb.Site.Models.Documentation.NamespaceModel

@{
	ViewBag.Title = Model.Name;
}

@section featured {
	<div id="home"></div>
	<section class="featured jumbotron jumbotron-warning mbl">
		<div class="container">
			<div class="title">
				<i class="logo pull-left"></i>
				<h1>@(Html.SiteName()).</h1>
				<h2 class="muted">A managed port of the Android Debug Bridge.</h2>
				<hr />
				<p class="text-center">
					<a href="https://madb.codeplex.com/" target="_blank" class="btn btn-lg"><i class="fa fa-external-link-square mrs" title="Project"></i><span class="">Project</span></a>
					<a href="https://madb.codeplex.com/SourceControl/latest#trunk/Managed.AndroidDebugBridge/" target="_blank" class="btn btn- btn-lg"><i class="fa fa-code-fork mrs" title="Source"></i><span class="">Source</span></a>
					<a href="https://madb.codeplex.com/releases" target="_blank" class="btn btn-lg"><i class="fa fa-download mrs" title="Download"></i><span class="">Download</span></a>
					<a href="https://madb.codeplex.com/workitem/list/basic" target="_blank" class="btn btn-lg"><i class="fa fa-bug mrs" title="Issues"></i><span class="">Issues</span></a>
					<a href="https://madb.codeplex.com/discussions" target="_blank" class="btn btn-lg"><i class="fa fa-quote-left mrs" title="Discussions"></i><span class="">Discussions</span></a>
				</p>
			</div>
		</div>
	</section>
}

@(Html.Partial("_AboutPartial"))
@(Html.Partial("_NugetPartial"))
@(Html.Partial("_LicensePartial"))

<div id="documentation">
	@(Html.Partial("_AdPartial"))
	<div class="panel panel-success pan">
		<div class="panel-heading"><h1 class="zero lowercase"><i class="fa fa-book mrm"></i>Documentation</h1></div>
		<div class="panel-body">
			@foreach(var ns in Model.Namespaces) {
				if(!ns.Ignore) {
					@(Html.Partial("_AdPartial"))
					@Html.DisplayFor(d => ns)
				}
			}
		</div>
	</div>
</div>

Madb.Site/Views/Documentation/Navigation.cshtml
@using Madb.Site.Models.Documentation;

@model NamespaceModel
@{
	const int scrollTopOffset = -70;
	var id = ViewContext.ParentActionViewContext.RouteData.Values["id"] == null ? "" : ViewContext.ParentActionViewContext.RouteData.Values["id"].ToString();
	var fullNav = Model.Name.Equals(id, StringComparison.InvariantCultureIgnoreCase);

}

@helper SafeNamespaceName(string ns) {
	if(ns.Equals(Model.Name)) {
		<text>@Model.Name</text>
	} else {
		<text>@ns.Substring(Model.Name.Length + 1)</text>
	}
}


@helper DisplayNamespace(NamespaceModel ns, int offset) {
	if(!ns.Ignore) {
		<li>
			<a data-expandable="click"
				 data-expandable-toggle="nav-expanded"
				 data-expandable-target="ul[data-id='@(ns.Id)']"
				 data-scroll="click"
				 data-scroll-offset="@(offset)"
				 href="@(Url.Action("Index", "Documentation", new { id = Model.Name }))#@ns.Id"
				 title="@ns.ToString()"
				 class="track"><i class="mll mrs fa fa-code"></i><span>@SafeNamespaceName(ns.Name)</span></a>
			@if(ns.Classes.Count > 0) {
				<ul class="nav nested mll" data-id="@ns.Id">
					@foreach(var nsx in ns.Namespaces.Where(m => m.Name != ns.Name)) {
						@DisplayNamespace(nsx, offset)
					}
					@foreach(var pm in ns.Classes) {
						@DisplayClass(pm, offset)
					}
				</ul>
			}
		</li>
	}
}


@helper DisplayRootNamespace(int offset) {
	var root = Model.Namespaces.First(m => m.Name == Model.Name);
	if(!root.Ignore) {
		<li>
			<a data-scroll="click" data-scroll-offset="@(offset)" href="@(Url.Action("Index", "Documentation", new { id = root.Name }))#@root.Id" class="track"><i class="mrs fa fa-code"></i><span>@root.Name</span></a>
			@if(root.Classes.Count > 0 || root.Namespaces.Count > 0) {
				<ul class="nav nested nav-always-expanded">
					@foreach(var ns in Model.Namespaces.Where(m => m.Name != root.Name)) {
						@DisplayNamespace(ns, offset)
					}
					@foreach(var c in root.Classes) {
						@DisplayClass(c,offset)
					}

				</ul>
			}
		</li>
	}
}
@helper DisplayClass(ClassModel cm, int offset) {
	if(!cm.Ignore) {
		<li>
			<a data-expandable="click" 
				 data-expandable-toggle="nav-expanded" 
				 data-expandable-target="ul[data-id='@(cm.Id)']" 
				 data-scroll="click" 
				 data-scroll-offset="@(offset)" 
				 href="@(Url.Action("Index", "Documentation", new { id = Model.Name }))#@cm.Id" title="@cm.ToString()" 
				 class="track"><i class="mll mrs fa fa-bolt"></i><span>@cm.Name</span></a>
			@if(cm.Properties.Count > 0 || cm.Methods.Count > 0) {
				<ul class="nav nested mll" data-id="@cm.Id">
					@foreach(var pm in cm.Properties) {
						@DisplayProperty(pm, offset)
					}
					@foreach(var m in cm.Methods) {
						@DisplayMethod(m, offset)
					}
				</ul>
			}
		</li>
	}
}

@helper DisplayProperty(PropertyModel pm, int offset) {
	if(!pm.Ignore) {
		<li><a data-scroll="click" data-scroll-offset="@(offset)" href="@(Url.Action("Index", "Documentation", new { id = Model.Name }))#@pm.Id" title="@pm.ToString()" class="track"><i class="mll mrs fa fa-asterisk"></i><span>@pm.Name</span></a></li>
	}
}

@helper DisplayMethod(MethodModel mm, int offset) {
	if(!mm.Ignore) {
		<li><a data-scroll="click" data-scroll-offset="@(offset)" href="@(Url.Action("Index", "Documentation", new { id = Model.Name }))#@mm.Id" title="@mm.ToString()" class="track"><i class="mll mrs fa fa-gavel"></i><span>@mm.Name</span></a></li>
	}
}

@if(fullNav) {
	<li>
		@DisplayRootNamespace(scrollTopOffset)
	</li>
} else {
	<li>
		<a data-scroll="click" data-scroll-offset="@(scrollTopOffset)" href="@(Url.Action("Index", "Documentation", new { id = Model.Name }))" class="track"><i class="mrs fa fa-code"></i><span>@Model.Name</span></a>
	</li>
}

Madb.Site/Views/Documentation/_AboutPartial.cshtml
<div id="about">
	@(Html.Partial("_AdPartial"))
	<div class="panel panel-success pan">
		<div class="panel-heading"><h1 class="zero lowercase"><i class="fa fa-question-circle mrm"></i>About</h1></div>
		<div class="panel-body">
			<p>
				This is a Managed port of the Android Debug Bridge to allow communication from .NET applications to Android devices.
				This wraps the same methods that the ddms uses to directly communicate with ADB. This gives more flexibility to the developer
				than launching an adb process and executing one of its built in commands.
			</p>
		</div>
	</div>
</div>

Madb.Site/Views/Documentation/_LicensePartial.cshtml
<div id="license">
	@(Html.Partial("_AdPartial"))
	<div class="panel panel-success pan">
		<div class="panel-heading"><h1 class="zero lowercase"><i class="fa fa-certificate mrm"></i>License</h1></div>
		<div class="panel-body">
			<div class="gist-container">
				@(Html.Action("Gist", new { controller = "assets", id = "3d408440566327fe5c62" }))
			</div>
		</div>
	</div>
</div>

Madb.Site/Views/Documentation/_NugetPartial.cshtml
<div id="nuget">
	@(Html.Partial("_AdPartial"))
	<div class="panel panel-success pan">
		<div class="panel-heading"><h1 class="zero lowercase"><i class="fa fa-download mrm"></i>Nuget</h1></div>
		<div class="panel-body">
			<div class="nuget-badge mtl">
				<code class="">PM&gt; <span data-id="Managed.Adb">Install-Package Managed.Adb</span></code>
				<div class="pull-right mtn4 mrs">
					<a title="copy" href="#" data-copy="click" data-copy-target="[data-id='Managed.Adb']" class="btn btn-round btn-info z-depth-1 mtml mrs"><i class="fa fa-copy"></i></a>
					<a title="Visit nuget.org" href="https://nuget.org/packages/managed.adb/" target="_blank" class="btn btn-round btn-success z-depth-1 mtml"><i class="fa fa-external-link"></i></a>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>